### ISSUE TITLE
Finished Weekly Reflection 5

### ISSUE THREAD

**Issue by Alex-Craig** [Berea-CS-Courses/capstone-project-Alex-Craig#16]
In this reflection I talked about hoping to accomplish:
- Adding the filters
- Adding a QR Code scanner for Menus
- Getting the wheel to reflect the chose color.

I would like feedback on:
- Creating the search filter section as it has given me the most trouble. The reflection has an image with the code from Yelp and my code for a comparison. The biggest problem is that there are 2 alias meanings, and the one I need is in subcode under the categories section.

**Comment by alfarozavalae** [comment]
Where is the second alias? Have you tested if the program does work with the other alias? Because if that is the case, that means we just need to figure out how to get the second one from the categories.
