### ISSUE TITLE
D1: Project Specification Statement (accidentally skipped issue step)

### ISSUE THREAD

**Issue by Alex-Craig** [Berea-CS-Courses/capstone-project-Alex-Craig#4]
Overview:

So the project that I have settled on completing is my Food Randomizer App that will try and randomize a food location based off the information given (covered in Concepts). With this app I hope to help friend groups eliminate the time it takes to choose somewhere to go and allows for more time spent hanging out rather than just searching. If enough time is available I also hope to add activities such as movies, mini golf, arcades, bowling, etc. to create an Activity Randomizer.

Concepts:

The main concept is to build more onto a basic wheel app that allows you to input the things you want to do inside and instead allows the app to do it for you, and gives you the information of the restaurant included. I hope to use the Google Places API and web scraping to create a website and/or app. My project will take in information such as the urgency/waiting time, how much you are willing to spend, measurements (km/mi), distance, displays the ratings and hours of the restaurant, and a possible option for a reroll as its major features. I also plan to add a search option that allows you to search based off of type of food to accomodate for allergies and dietary restrictions, but most restaurants already have alternative options so this might be dropped.

Requirements:

-Software must be able to scrape information from the web using Google Maps/Places API
-Software must be able to randomly generate a restaurant based off information given
-Software must be able to use user's location, map data, or search by zip
-Software must be able to have an open restaurants only mode
-Software must be able to separate restaurants based off waiting times, prices, and distance
-Software must be able to run on an app and/or web browser
-Software must be able to implement a reroll function.
-Software might be able to separate restaurants based off type of food.
-Software must be able to display directions to the chosen restaurant.
-Software must be able to sort restaurants based off of food types (Asian, Mexican, Italian, etc.)

**Comment by belainehi** [comment]
Great job writing out the purpose of your app clearly. A suggestion I could give would be to clearly define the scope of your app so you clearly know what features to implement in your application (for instance how would a search option serve the purpose of getting a random restaurant suggestion?). Another suggestion is to write out how data flows in your application from user input to information the user gets back. Defining the non-technical requirements (qualities or constraints that the software must have or comply with, but which are not operations that will be automated) like where you will host your web application was part of the assignment requirement.

**Comment by Bryar-Frank** [comment]
You may close this issue
