### ISSUE TITLE
D2 - Project Decomposition

### ISSUE THREAD

**Issue by Alex-Craig** [Berea-CS-Courses/capstone-project-Alex-Craig#5]
**Components**
- Take in the users location
- Use Google Places API to display restaurants based on the location of the users input.
- Filter the restaurants by availability, distance, price range, and food type (possibly web scraping).
- Display the list of restaurants to allow the user to select certain restaurants.
- Spin the wheel and choose a random restaurant.
- Allow the user to spin again if needed.
- Get directions for chosen restaurant.

**Understanding the components**
- By writing out my components in a list in order based on what I want the app to do seems a lot easier than I first assumed and was worried about. When I see this list I realize that the previous step is required for the next step. Now I have a timeline and backbone of what I need to get done.

**Breaking up components**
- My components are pretty much broken up into the bits and pieces that I need to work on. However I could break up the filtering process into different steps but I think the Google Places API will already display the distance, price range, etc.

**Prioritize**
- Learn Google Places API (https://www.youtube.com/watch?v=5oG2Q2GMOBE&ab_channel=GoogleDevelopers)
- Everything else is in the order needed
- Putting everything together into an app and/or website

**Comment by Bryar-Frank** [comment]
Please leave Issue open until feedback is given. You can close issues after reviewing the feedback received. Thank you!

**Comment by robinsonkal** [comment]
I think maybe the components part of the document should solely focus on large components. Like maybe instead of having "take users location" under components, you would have Google maps API and then later break the google maps API down into different needed functions like "take in users location".

**Comment by schweinsbergs** [comment]
It's really good that you've figured out enough HTML to give us the demonstration that you did in class! It was really useful, and I think it's a good first step in your progress. 

That said, I think that this document needs a little more breaking down; 'figuring out how to put it on an app/website'-- I think you need to figure out if you want to make this an app or a website first, and then figure out what needs to be done from there. Do you need a host for a website? Do you need to learn HTML for frontend?

**Comment by Bryar-Frank** [comment]
While this is a fantastic breakdown of the "step-by-step" process your application will apply, I do not think it meets the requirements of the assignment. There is a good sense as to what will be going on behind the screen; however, a more explicitly stating a hierarchy of your components will be help to visualize what needs to be implemented next in your project. For example: under "take in user's location", what do you plan to implement behind that action? Will you need to graphically make text boxes? will the data be stored on a file in there phone?. Documenting the nuisances of your components will help more with understanding of your whole system. Also, in the "Understanding your components section, there is no breakdown of components interaction, needs, or their overall importance. For example: how will the "take in user's location" interact with Google's API? This is a really good start, but please keep these changes in mind for the midterm documentation.
